# -*- coding: utf-8 -*-
"""Pokemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9dajDNgK79kbbA3D-YyFJvM_JH_Uai6

# Pokemon
"""

import pandas as pd

"""Abrir el csv con datos del pokemon"""

pokemon = pd.read_csv('pokemon.csv')

print(pokemon)

poderosos = pokemon.loc[pokemon["Attack"] >= 100]

print(poderosos)

mitad = pokemon.loc[(pokemon["#"] > 200) & (pokemon["#"] < 300)]

print(mitad)

fuego_y_agua = pokemon.loc[(pokemon["Type 1"] == "Water") | (pokemon["Type 1"] == "Fire")]

# operadores logicos pueden ser & (and), | (or)

print(fuego_y_agua)

legendarios_hielo = pokemon.loc[(pokemon["Legendary"] == True) & (pokemon["Type 1"] == "Ice")]

print(legendarios_hielo[["#", "Name", "Type 1", "Type 2", "Attack", "Defense"]])

dos_a_cuatro = pokemon.loc[(pokemon["#"] >= 200) & (pokemon["#"] <= 400)]

print(dos_a_cuatro)

poderosos_legendarios = pokemon.loc[(pokemon["Attack"] >= 100) & (pokemon["Legendary"] == True)]

print(poderosos_legendarios["Name"])

"""Es posible usar la función query para hacer más "natural" la búsqueda"""

#poderosos_fantasmas = pokemon.query("Attack >= 10 and `Type 1` == 'Ghost'")

poderosos_fantasmas = pokemon.loc[(pokemon["Attack"] >= 40) & (pokemon["Type 1"] == "Ghost")]

print(poderosos_fantasmas)

pf = poderosos_fantasmas[["Name", "Attack", "Defense"]]

print(pf)

print(pf.sort_values(by="Attack"))

print(pf.sort_values(by="Attack", ascending=False))

pf_ordenados = pf.sort_values(by="Attack", ascending=False)

print(pf_ordenados.head(5))

print(pokemon.loc[(pokemon["Attack"] >= 40) & (pokemon["Type 1"] == "Ghost")].sort_values(by="Attack", ascending=False).head(3)[["Name", "Attack"]])

"""Se pueden utilizar ciclos para recorrer la información"""

for i in range(len(pokemon)):
    if (pokemon.loc[i]["Legendary"] and pokemon.loc[i]["Type 1"] == "Fire"):
        print(pokemon.loc[i]["Name"] + " - " + str(pokemon.loc[i]["Attack"]) + "/" + str(pokemon.loc[i]["Defense"]))